name = "TrixiShallowWater"
uuid = "804cb1fc-5b08-4398-a671-a789bfe091b3"
authors = ["Andrew R. Winters <andrew.ross.winters@liu.se>", "Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.0-pre"

[compat]
julia = "1.8"
